### ISSUE TITLE
sync original mapfiles is slow ... should we use a tarball?

### ISSUE THREAD

**Issue by cehbrecht** [cedadev/c3s-esgf-tools#2]
The globus sync for the original mapfiles is slow because it needs to go through the directory hierarchy ... taking minutes. This is still acceptable. 

An alternative could be to provide a mapfile tarball on the master side, which gets copied to the clients.

**Comment by alaniwi** [comment]
I think that @RuthPetrie would prefer to avoid the additional work of creating a tarball. In any case, the original sync is a one-off operation, and a tarball doesn't help very much with an incremental addition of datasets.

**Comment by alaniwi** [comment]
I created a tarball when it was taking people "forever" to obtain the mapfiles. But if we are talking about a few minutes, then I think (as you say, @cehbrecht) that is acceptable. Unfortunately the filesystem on the server is not really optimised for lots of small files, so until they are in memory cache on the server it will be slow, and even if we had an rsync server for example, it would not change this fact.

Sorry Carsten, I am going to close this as "won't fix".
